name: Node.js CI + Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .

      - name: Run Tests
        run: npm test

  deploy:
    # On déploie uniquement sur push, pas sur pull request
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: lint-and-test  # attend que lint & test passent

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site to artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # suppose que ton index.html est à la racine

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
